# Generated by Django 4.2.5 on 2023-10-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist_list',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='artist_list',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category_list',
            name='cat_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post_list',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
