# Generated by Django 4.2.5 on 2023-10-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_alter_artist_list_contact_alter_artist_list_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_list',
            name='artist_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
