# Generated by Django 4.2.5 on 2023-10-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0003_post_list_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist_list',
            name='contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
